stages:
  - test

.job:
  image: node:18

  stage: test

  before_script:
    - cd $DIR
    - yarn install --immutable

  script:
    - yarn test
    - yarn build

  cache:
    key: $CI_JOB_NAME
    paths:
      - $DIR/.yarn
      - $DIR/node_modules/

include:
  - local: '/client/.gitlab-ci.yml'
  - local: '/server/.gitlab-ci.yml'
